# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maketMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cancelRequestPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelRequestPushButton.setGeometry(QtCore.QRect(470, 360, 88, 25))
        self.cancelRequestPushButton.setObjectName("cancelRequestPushButton")
        self.cancelRequestPushButton.setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 20, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_2.setVisible(False)
        self.logsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.logsPushButton.setGeometry(QtCore.QRect(10, 370, 88, 25))
        self.logsPushButton.setObjectName("logsPushButton")
        self.sendRequestPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendRequestPushButton.setGeometry(QtCore.QRect(190, 200, 131, 25))
        self.sendRequestPushButton.setObjectName("sendRequestPushButton")
        self.inputSleepTimeTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputSleepTimeTextBox.setGeometry(QtCore.QRect(10, 100, 113, 25))
        self.inputSleepTimeTextBox.setObjectName("inputSleepTimeTextBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.label.setObjectName("label")
        self.inputNumberTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNumberTextBox.setGeometry(QtCore.QRect(10, 40, 113, 25))
        self.inputNumberTextBox.setObjectName("inputNumberTextBox")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(410, 40, 66, 17))
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 141, 17))
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(200, 230, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 583, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cancelRequestPushButton.setText(_translate("MainWindow", "Отмена"))
        self.label_2.setText(_translate("MainWindow", "Результат:"))
        self.logsPushButton.setText(_translate("MainWindow", "Logs"))
        self.sendRequestPushButton.setText(_translate("MainWindow", "Удвоить число"))
        self.label.setText(_translate("MainWindow", "Введите число:"))
        self.label_3.setText(_translate("MainWindow", "Введите задержку:"))
